### PR TITLE
Fix autocomplete

### PR DESCRIPTION
**Pull request by Mitsuroseba**

### CODE REVIEW

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build34
Behat tests: standard file http://95.85.26.139/build34/build_reports/report.html

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/34/
Test PASSed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build35
Behat tests: standard file http://95.85.26.139/build35/build_reports/report.html

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/35/
Test PASSed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build36
Behat tests: standard file http://95.85.26.139/build36/build_reports/report.html

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/36/
Test PASSed.

**Comment by Mitsuroseba** [comment]
test this please

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build37
Behat tests: standard file http://95.85.26.139/build37/build_reports/report.html

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/37/
Test PASSed.

**Pull request merged**
