### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Mitsuroseba**

### CODE REVIEW

**Comment by Mitsuroseba** [comment]
test this please

**Comment by naebal** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by Mitsuroseba** [comment]
ok to test

**Comment by Mitsuroseba** [comment]
test this please

**Comment by Mitsuroseba** [comment]
test this please

**Comment by Mitsuroseba** [comment]
ok to test

**Comment by naebal** [comment]
Build comment file: 
--------------
===============

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/2/

**Build Log**
*last 25 lines*

 ```
[...truncated 6809 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/453f6b59d4fd55350916d06a69be196e5c90c659
	at sun.reflect.GeneratedConstructorAccessor138.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/453f6b59d4fd55350916d06a69be196e5c90c659
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/3/

**Build Log**
*last 25 lines*

 ```
[...truncated 6810 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/453f6b59d4fd55350916d06a69be196e5c90c659
	at sun.reflect.GeneratedConstructorAccessor138.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/453f6b59d4fd55350916d06a69be196e5c90c659
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build4

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/4/

**Build Log**
*last 25 lines*

 ```
[...truncated 6916 lines...]
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/44ce1041f599c641527bf616bd426671b7f3a07b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/44ce1041f599c641527bf616bd426671b7f3a07b
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by Mitsuroseba** [comment]
test this please

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build5

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/5/

**Build Log**
*last 25 lines*

 ```
[...truncated 7019 lines...]
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/44ce1041f599c641527bf616bd426671b7f3a07b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/44ce1041f599c641527bf616bd426671b7f3a07b
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build6

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/6/

**Build Log**
*last 25 lines*

 ```
[...truncated 7029 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/0f0e512dcf3a9dd82a78daccf5a8bb87df3e673c
	at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/0f0e512dcf3a9dd82a78daccf5a8bb87df3e673c
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build7

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/7/

**Build Log**
*last 25 lines*

 ```
[...truncated 7041 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/d0c5fbc12079b132eec26e18fc28704a6aa57b0a
	at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/d0c5fbc12079b132eec26e18fc28704a6aa57b0a
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build8

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/8/

**Build Log**
*last 25 lines*

 ```
[...truncated 7067 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5b22cd71e1839f6369e01d2d41b8e802a91f67ac
	at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5b22cd71e1839f6369e01d2d41b8e802a91f67ac
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by Mitsuroseba** [comment]
test this please

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build9

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/9/

**Build Log**
*last 25 lines*

 ```
[...truncated 7030 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5b22cd71e1839f6369e01d2d41b8e802a91f67ac
	at sun.reflect.GeneratedConstructorAccessor150.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5b22cd71e1839f6369e01d2d41b8e802a91f67ac
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build10

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/10/

**Build Log**
*last 25 lines*

 ```
[...truncated 7050 lines...]
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/a0ca65a48075116d2d6bbe2ebcd55d13a8126f29
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/a0ca65a48075116d2d6bbe2ebcd55d13a8126f29
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/11/

**Build Log**
*last 25 lines*

 ```
[...truncated 6836 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/36682d1a74054a3ddb5ee7a3a9e9e980f300730c
	at sun.reflect.GeneratedConstructorAccessor158.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/36682d1a74054a3ddb5ee7a3a9e9e980f300730c
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/12/

**Build Log**
*last 25 lines*

 ```
[...truncated 7543 lines...]
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5145c2de9901e7f87575da3e811a12aaae86dbc6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5145c2de9901e7f87575da3e811a12aaae86dbc6
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by Mitsuroseba** [comment]
test this please

**Comment by naebal** [comment]
Build comment file: 
--------------
===============

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/13/

**Build Log**
*last 25 lines*

 ```
[...truncated 7541 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5145c2de9901e7f87575da3e811a12aaae86dbc6
	at sun.reflect.GeneratedConstructorAccessor160.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5145c2de9901e7f87575da3e811a12aaae86dbc6
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by Mitsuroseba** [comment]
test this please

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build14

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/14/

**Build Log**
*last 25 lines*

 ```
[...truncated 7774 lines...]
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1789)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5145c2de9901e7f87575da3e811a12aaae86dbc6
	at sun.reflect.GeneratedConstructorAccessor160.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	... 13 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/malmostad/vuxenforvaltningens_informationsportal/statuses/5145c2de9901e7f87575da3e811a12aaae86dbc6
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 14 more
```

Test FAILed.

**Comment by Mitsuroseba** [comment]
test this please

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build15
Behat tests: standard file http://95.85.26.139/build15/build_reports/report.html

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/15/
Test PASSed.

**Comment by naebal** [comment]
Build comment file: 
--------------
===============
Build site installed at http://95.85.26.139/build16
Behat tests: standard file http://95.85.26.139/build16/build_reports/report.html

--------------

Refer to this link for build results (access rights to CI server needed): 
http://95.85.26.139:8080//job/malmo_PR_BUILDER/16/
Test PASSed.

**Pull request merged**
