### PR TITLE
MAL-333 Set message if search result is empty

### PR DESCRIPTION
**Pull request by gajdamaka**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build66/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build66
Behat tests: standard file http://128.199.38.86/malmo_build66/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/66/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build67/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build67
Behat tests: standard file http://128.199.38.86/malmo_build67/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/67/

**Comment by aapetrov** [comment]
Retest it please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build68/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build68
Behat tests: standard file http://128.199.38.86/malmo_build68/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/68/

**Pull request merged**
