### PR TITLE
Returt flex courses functionality

### PR DESCRIPTION
**Pull request by gajdamaka**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build29/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build29/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build29/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build29
Behat tests: standard file http://128.199.38.86/malmo_build29/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/29/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build30/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build30/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build30/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build30
Behat tests: standard file http://128.199.38.86/malmo_build30/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/30/

**Comment by aapetrov** [comment]
Retest this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build31/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build31/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build31/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build31
Behat tests: standard file http://128.199.38.86/malmo_build31/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/31/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build33/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build33/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build33/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build33
Behat tests: standard file http://128.199.38.86/malmo_build33/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/33/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build35/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build35/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build35/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build35
Behat tests: standard file http://128.199.38.86/malmo_build35/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/35/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build36/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build36/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build36/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build36
Behat tests: standard file http://128.199.38.86/malmo_build36/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/36/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build37/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build37/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build37/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build37
Behat tests: standard file http://128.199.38.86/malmo_build37/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/37/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>5</strong> JSHint: modules standard file http://128.199.38.86/malmo_build38/build_reports/modulesjshint.txt
<strong>6800</strong> JSHint: profile standard file http://128.199.38.86/malmo_build38/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build38
Behat tests: standard file http://128.199.38.86/malmo_build38/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/38/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>5</strong> JSHint: modules standard file http://128.199.38.86/malmo_build39/build_reports/modulesjshint.txt
<strong>6800</strong> JSHint: profile standard file http://128.199.38.86/malmo_build39/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build39
Behat tests: standard file http://128.199.38.86/malmo_build39/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/39/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build40/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build40
Behat tests: standard file http://128.199.38.86/malmo_build40/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/40/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build41/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build41
Behat tests: standard file http://128.199.38.86/malmo_build41/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/41/

**Pull request merged**
