### PR TITLE
Enable AJAX 

### PR DESCRIPTION
**Pull request by gajdamaka**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build52/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build52
Behat tests: standard file http://128.199.38.86/malmo_build52/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/52/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build53/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build53
Behat tests: standard file http://128.199.38.86/malmo_build53/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/53/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build54/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build54
Behat tests: standard file http://128.199.38.86/malmo_build54/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/54/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build55/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build55
Behat tests: standard file http://128.199.38.86/malmo_build55/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/55/

**Comment by aapetrov** [comment]
Retest this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build56/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build56
Behat tests: standard file http://128.199.38.86/malmo_build56/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/56/

**Pull request merged**
