### PR TITLE
Unpublished node edit. Prevent notification

### PR DESCRIPTION
**Pull request by OlyaRybak**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build57/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build57
Behat tests: standard file http://128.199.38.86/malmo_build57/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/57/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build58/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build58
Behat tests: standard file http://128.199.38.86/malmo_build58/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/58/

**Comment by OlyaRybak** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build59/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build59
Behat tests: standard file http://128.199.38.86/malmo_build59/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/59/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build65/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build65
Behat tests: standard file http://128.199.38.86/malmo_build65/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/65/

**Pull request merged**
