### PR TITLE
Mal 310

### PR DESCRIPTION
**Pull request by PavelLoparev**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/10/

**Build Log**
*last 25 lines*

 ```
[...truncated 7661 lines...]
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
changed: [localhost]

TASK: [Remove live search server] ********************************************* 
failed: [localhost] => {"changed": true, "cmd": "APP_ENV=dev drush eval 'search_api_server_delete('apache_solr');'", "delta": "0:00:03.905404", "end": "2015-10-02 10:00:02.629933", "rc": 255, "start": "2015-10-02 09:59:58.724529", "warnings": []}
stderr: PHP Fatal error:  Call to a member function delete() on boolean in /var/www/malmo_build10/profiles/mal/modules/contrib/search_api/search_api.module on line 2504
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to a member function delete() on boolean in
/var/www/malmo_build10/profiles/mal/modules/contrib/search_api/search_api.module,
line 2504

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jenkins/reinstall.retry

localhost                  : ok=22   changed=15   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by PavelLoparev** [comment]
Test this please

**Comment by M1r1k** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/15/

**Build Log**
*last 25 lines*

 ```
[...truncated 7661 lines...]
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
changed: [localhost]

TASK: [Remove live search server] ********************************************* 
failed: [localhost] => {"changed": true, "cmd": "APP_ENV=dev drush eval 'search_api_server_delete('apache_solr');'", "delta": "0:00:04.189061", "end": "2015-10-05 03:45:06.159415", "rc": 255, "start": "2015-10-05 03:45:01.970354", "warnings": []}
stderr: PHP Fatal error:  Call to a member function delete() on boolean in /var/www/malmo_build15/profiles/mal/modules/contrib/search_api/search_api.module on line 2504
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to a member function delete() on boolean in
/var/www/malmo_build15/profiles/mal/modules/contrib/search_api/search_api.module,
line 2504

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jenkins/reinstall.retry

localhost                  : ok=22   changed=15   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by M1r1k** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/16/

**Build Log**
*last 25 lines*

 ```
[...truncated 7661 lines...]
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
changed: [localhost]

TASK: [Remove live search server] ********************************************* 
failed: [localhost] => {"changed": true, "cmd": "APP_ENV=dev drush eval 'search_api_server_delete('apache_solr');'", "delta": "0:00:04.213647", "end": "2015-10-05 04:03:36.212794", "rc": 255, "start": "2015-10-05 04:03:31.999147", "warnings": []}
stderr: PHP Fatal error:  Call to a member function delete() on boolean in /var/www/malmo_build16/profiles/mal/modules/contrib/search_api/search_api.module on line 2504
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to a member function delete() on boolean in
/var/www/malmo_build16/profiles/mal/modules/contrib/search_api/search_api.module,
line 2504

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jenkins/reinstall.retry

localhost                  : ok=22   changed=15   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by PavelLoparev** [comment]
test this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/18/

**Build Log**
*last 25 lines*

 ```
[...truncated 7661 lines...]
skipping: [localhost]

TASK: [Clear drush cache] ***************************************************** 
skipping: [localhost]

TASK: [Rebuilding drupal registry] ******************************************** 
changed: [localhost]

TASK: [Remove live search server] ********************************************* 
failed: [localhost] => {"changed": true, "cmd": "APP_ENV=dev drush eval 'search_api_server_delete('apache_solr');'", "delta": "0:00:04.474374", "end": "2015-10-05 06:21:00.935025", "rc": 255, "start": "2015-10-05 06:20:56.460651", "warnings": []}
stderr: PHP Fatal error:  Call to a member function delete() on boolean in /var/www/malmo_build18/profiles/mal/modules/contrib/search_api/search_api.module on line 2504
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Call to a member function delete() on boolean in
/var/www/malmo_build18/profiles/mal/modules/contrib/search_api/search_api.module,
line 2504

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jenkins/reinstall.retry

localhost                  : ok=22   changed=15   unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build19/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build19/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build19/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build19
Behat tests: standard file http://128.199.38.86/malmo_build19/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/19/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build23/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build23/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build23/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build23
Behat tests: standard file http://128.199.38.86/malmo_build23/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/23/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build25/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build25/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build25/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build25
Behat tests: standard file http://128.199.38.86/malmo_build25/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/25/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>23</strong> JSHint: modules standard file http://128.199.38.86/malmo_build26/build_reports/modulesjshint.txt
<strong>3</strong> JSHint: themes standard file http://128.199.38.86/malmo_build26/build_reports/themesjshint.txt
<strong>6820</strong> JSHint: profile standard file http://128.199.38.86/malmo_build26/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build26
Behat tests: standard file http://128.199.38.86/malmo_build26/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/26/

**Pull request merged**
