### PR TITLE
MAL-305 | small fixes

### PR DESCRIPTION
**Pull request by redlable**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Can one of the admins verify this patch? Use "o+k to test" or ''t+est this please" for manual build execution.

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/5/

**Build Log**
*last 25 lines*

 ```
[...truncated 7577 lines...]
TASK: [Creating backup folder] ************************************************ 
ok: [localhost]

TASK: [Making regular backup] ************************************************* 
skipping: [localhost]

TASK: [Check if latest backup exists] ***************************************** 
ok: [localhost]

TASK: [Create initial backup from staging] ************************************ 
skipping: [localhost]

TASK: [Downloading latest backup] ********************************************* 
failed: [localhost] => {"dest": "/var/www/backup/latest.sql.gz", "failed": true, "gid": 1000, "group": "jenkins", "mode": "0644", "owner": "jenkins", "response": "Request failed: <urlopen error timed out>", "size": 1626604, "state": "file", "status_code": -1, "uid": 1000, "url": "http://propeople:givemebackup@95.85.26.139/backup/latest.sql.gz"}
msg: Request failed

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jenkins/reinstall.retry

localhost                  : ok=3    changed=0    unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/24/

**Build Log**
*last 25 lines*

 ```
[...truncated 7577 lines...]
TASK: [Creating backup folder] ************************************************ 
ok: [localhost]

TASK: [Making regular backup] ************************************************* 
skipping: [localhost]

TASK: [Check if latest backup exists] ***************************************** 
ok: [localhost]

TASK: [Create initial backup from staging] ************************************ 
skipping: [localhost]

TASK: [Downloading latest backup] ********************************************* 
failed: [localhost] => {"dest": "/var/www/backup/latest.sql.gz", "failed": true, "gid": 1000, "group": "jenkins", "mode": "0644", "owner": "jenkins", "response": "Request failed: <urlopen error timed out>", "size": 1626604, "state": "file", "status_code": -1, "uid": 1000, "url": "http://propeople:givemebackup@95.85.26.139/backup/latest.sql.gz"}
msg: Request failed

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jenkins/reinstall.retry

localhost                  : ok=3    changed=0    unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Comment by aapetrov** [comment]
Retest this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============

--------------
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/32/

**Build Log**
*last 25 lines*

 ```
[...truncated 7577 lines...]
TASK: [Creating backup folder] ************************************************ 
ok: [localhost]

TASK: [Making regular backup] ************************************************* 
skipping: [localhost]

TASK: [Check if latest backup exists] ***************************************** 
ok: [localhost]

TASK: [Create initial backup from staging] ************************************ 
skipping: [localhost]

TASK: [Downloading latest backup] ********************************************* 
failed: [localhost] => {"dest": "/var/www/backup/latest.sql.gz", "failed": true, "gid": 1000, "group": "jenkins", "mode": "0644", "owner": "jenkins", "response": "Request failed: <urlopen error timed out>", "size": 1626604, "state": "file", "status_code": -1, "uid": 1000, "url": "http://propeople:givemebackup@95.85.26.139/backup/latest.sql.gz"}
msg: Request failed

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/jenkins/reinstall.retry

localhost                  : ok=3    changed=0    unreachable=0    failed=1   

Build step 'Execute shell' marked build as failure
```

**Pull request merged**
