### PR TITLE
Change aliases

### PR DESCRIPTION
**Pull request by gajdamaka**

### CODE REVIEW

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build73/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build73
Behat tests: standard file http://128.199.38.86/malmo_build73/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/73/

**Comment by gajdamaka** [comment]
test this

**Comment by gajdamaka** [comment]
Retest it please

**Comment by aapetrov** [comment]
Retest this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build74/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build74
Behat tests: standard file http://128.199.38.86/malmo_build74/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/74/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build75/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build75
Behat tests: standard file http://128.199.38.86/malmo_build75/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/75/

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build80/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build80
Behat tests: standard file http://128.199.38.86/malmo_build80/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/80/

**Comment by aapetrov** [comment]
Retest this please

**Comment by ffw-bot-ua** [comment]
Build comment file: 
--------------
===============
<strong>6796</strong> JSHint: profile standard file http://128.199.38.86/malmo_build81/build_reports/profilejshint.txt
Build site installed at http://128.199.38.86/malmo_build81
Behat tests: standard file http://128.199.38.86/malmo_build81/build_reports/report.html

--------------
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://128.199.38.86:8080/job/MALMO_PR_BUILDER/81/

**Pull request merged**
